<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Catalogo.cs" />
    <Compile Remove="Data\Persona.cs" />
    <Compile Remove="Data\Personacontacto.cs" />
    <Compile Remove="Data\Personadireccion.cs" />
    <Compile Remove="Data\Personadocumento.cs" />
    <Compile Remove="Data\Personanatural.cs" />
    <Compile Remove="Data\Personavinculacion.cs" />
    <Compile Remove="Repositorios\AreaObjetivoCriterioRepository.cs" />
    <Compile Remove="Repositorios\AreaObjetivoCriterioResumenViewRepository.cs" />
    <Compile Remove="Repositorios\AreaObjetivoCriterioViewRepository.cs" />
    <Compile Remove="Repositorios\AreaObjetivoRepository.cs" />
    <Compile Remove="Repositorios\AreaObjetivoViewRepository.cs" />
    <Compile Remove="Repositorios\AreaRepository.cs" />
    <Compile Remove="Repositorios\AreaViewRepository.cs" />
    <Compile Remove="Repositorios\AtencionRepository.cs" />
    <Compile Remove="Repositorios\AtencionTerapiaRepository.cs" />
    <Compile Remove="Repositorios\BaseEntityRepository.cs" />
    <Compile Remove="Repositorios\BaseEntityThreeIdsRepository.cs" />
    <Compile Remove="Repositorios\BaseEntityTwoIdsRepository.cs" />
    <Compile Remove="Repositorios\BaseRepository.cs" />
    <Compile Remove="Repositorios\BaseRepositoryView.cs" />
    <Compile Remove="Repositorios\CatalogoRepository.cs" />
    <Compile Remove="Repositorios\ComprobanteDetalleRepository.cs" />
    <Compile Remove="Repositorios\ComprobanteDetalleViewRepository.cs" />
    <Compile Remove="Repositorios\ComprobantePagoRepository.cs" />
    <Compile Remove="Repositorios\ComprobantePagoViewRepository.cs" />
    <Compile Remove="Repositorios\ComprobanteRepository.cs" />
    <Compile Remove="Repositorios\ComprobanteResumenViewRepository.cs" />
    <Compile Remove="Repositorios\ComprobanteViewRepository.cs" />
    <Compile Remove="Repositorios\ConceptoCobroRepository.cs" />
    <Compile Remove="Repositorios\ConceptoCobroViewRepository.cs" />
    <Compile Remove="Repositorios\DestrezaRepository.cs" />
    <Compile Remove="Repositorios\DireccionRepository.cs" />
    <Compile Remove="Repositorios\DireccionViewRepository.cs" />
    <Compile Remove="Repositorios\FilialViewRepository.cs" />
    <Compile Remove="Repositorios\ModeloRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteAlergiaRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteAlergiaViewRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteNivelLenguajeRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteNivelLenguajeViewRepository.cs" />
    <Compile Remove="Repositorios\ParticipantePersonaAutorizadaRepository.cs" />
    <Compile Remove="Repositorios\ParticipantePersonaAutorizadaViewRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteResumenViewRepository.cs" />
    <Compile Remove="Repositorios\ParticipanteViewRepository.cs" />
    <Compile Remove="Repositorios\PeriodoRepository.cs" />
    <Compile Remove="Repositorios\PeriodoViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaAntecedenteRepository.cs" />
    <Compile Remove="Repositorios\PersonaAntecedenteViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaContactoRepository.cs" />
    <Compile Remove="Repositorios\PersonaContactoViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaDireccionRepository.cs" />
    <Compile Remove="Repositorios\PersonaDireccionViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaDocumentoRepository.cs" />
    <Compile Remove="Repositorios\PersonaDocumentoViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaNaturalRepository.cs" />
    <Compile Remove="Repositorios\PersonaNaturalViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaRepository.cs" />
    <Compile Remove="Repositorios\PersonaResumenBasicoViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaResumenViewRepository.cs" />
    <Compile Remove="Repositorios\PersonaVinculacionRepository.cs" />
    <Compile Remove="Repositorios\PersonaVinculacionViewRepository.cs" />
    <Compile Remove="Repositorios\PuntuacionGrupoRepository.cs" />
    <Compile Remove="Repositorios\Repository.cs" />
    <Compile Remove="Repositorios\SalonViewRepository.cs" />
    <Compile Remove="Repositorios\ServicioRepository.cs" />
    <Compile Remove="Repositorios\SesionCriterioActividadRepository.cs" />
    <Compile Remove="Repositorios\SesionCriterioRepository.cs" />
    <Compile Remove="Repositorios\SesionCriterioViewRepository.cs" />
    <Compile Remove="Repositorios\SesionRepository.cs" />
    <Compile Remove="Repositorios\SesionResumenViewRepository.cs" />
    <Compile Remove="Repositorios\SesionTerapeutaRepository.cs" />
    <Compile Remove="Repositorios\SesionTerapeutaViewRepository.cs" />
    <Compile Remove="Repositorios\SesionViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaHorarioRepository.cs" />
    <Compile Remove="Repositorios\TerapiaHorarioViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaParticipanteRepository.cs" />
    <Compile Remove="Repositorios\TerapiaParticipanteResumenViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaParticipanteViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPeriodoRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPeriodoResumenViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPlanAreaRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPlanAreaViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPlanRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPlanResumenViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaPlanViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaRepository.cs" />
    <Compile Remove="Repositorios\TerapiaResumenViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaTerapeutaRepository.cs" />
    <Compile Remove="Repositorios\TerapiaTerapeutaViewRepository.cs" />
    <Compile Remove="Repositorios\TerapiaViewRepository.cs" />
    <Compile Remove="Repositorios\UbigeoRepository.cs" />
    <Compile Remove="Repositorios\UbigeoViewRepository.cs" />
    <Compile Remove="Repositorios\UsuarioRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />
    <PackageReference Include="MySql.Data" Version="8.4.0" />
    <PackageReference Include="MySql.Data.EntityFramework" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaTerapeutico.Core\SistemaTerapeutico.Core.csproj" />
  </ItemGroup>

</Project>
